.build deps:
  stage: build
  tags: [io, docker-engine]
  interruptible: true
  script:
    - !reference [.echo global envs, script]
    - docker pull ${DEPS_IMAGE} || docker pull ${DEPS_IMAGE_MASTER} || true
    - docker build --target deps -t ${DEPS_IMAGE}
      --build-arg NODE_IMAGE=${NODE_IMAGE}
      --cache-from ${DEPS_IMAGE}
      --cache-from ${DEPS_IMAGE_MASTER}
      -f ./docker/Dockerfile.app .
    - docker push ${DEPS_IMAGE}
