.deploy app:
  image:
    name: alpine/helm:3.14.0
    entrypoint: ['']
  tags: [io, docker-exec]
  interruptible: true
  script:
    - !reference [.echo global envs, script]
    - >
      echo -e "
      ☸️ DEPLOY ENV VARIABLES:\n
      - HELM_RELEASE_NAME=${HELM_RELEASE_NAME}\n
      - DC=${DC}\n
      - CLUSTER=${CLUSTER}\n
      - DOMAINS=${DOMAINS}\n
      - APP_IMAGE_NAME=${APP_IMAGE_NAME}"
    - helm --kube-context ${CLUSTER}-${DC} upgrade ${HELM_RELEASE_NAME} ./deploy/kit-docs
      -i --atomic --wait-for-jobs
      --timeout 6m --history-max 1
      ${HELM_VALUES_EXTRA:+-f $HELM_VALUES_EXTRA}
      --set image.repository="${DOCKER_NAMESPACE}/${APP_IMAGE_NAME}"
      --set image.tag="${IMAGE_TAG}"
      --set service.deis.domains="{${DOMAINS}}"
      --set annotations.ci_job_url="${CI_JOB_URL}"
