# RAG Repo Indexer
# Подробнее: https://confluence.2gis.ru/pages/viewpage.action?pageId=570463874
# Сорс: https://gitlab.2gis.ru/ds/llms/aiemp/rag-repo-indexer/-/blob/master/indexing.yml?ref_type=heads
include:
  - project: 'ds/llms/aiemp/rag-repo-indexer'
    ref: 'master'
    file: 'indexing.yml'

# Переопределяем джобу из инклюда выше, чтобы она не запускалась по дефолту
rag_index:
  rules:
    - when: never

.rag index:
  stage: index
  extends: rag_index
  tags: [io, docker]
  interruptible: true

.rag index docs refs:
  stage: index
  image: ${DEPS_IMAGE}
  tags: [io, docker]
  interruptible: true
  script:
    - ln -s /app/node_modules ./node_modules
    - npm run rag:index-docs-references
