.tests_screen:
  stage: ui test
  tags: [io, docker-compose]
  allow_failure: true
  parallel:
    matrix:
      - PROJECT: ['chromium', 'webkit mobile', 'firefox dark']
  variables:
    JOB_UID: ${CI_PIPELINE_ID}
  before_script:
    - !reference [.echo global envs, script]
    - docker build -t playwright-docs -f ./docker/Dockerfile.playwright .
  script:
    - >
      docker run --rm --ipc=host
      -v ./tests:/app/tests
      -v ./src:/app/src
      -v ./tsconfig.json:/app/tsconfig.json
      -v ./playwright.config.ts:/app/playwright.config.ts
      -v ./allure-results:/app/allure-results
      -e APP_URL=${APP_URL}
      -e CI=${CI}
      playwright-docs
      npm run screen:test:run -- --project="$PROJECT"
  after_script:
    - cd ./docker
    - docker compose run --rm --quiet-pull allure upload
      --ci-type gitlab
      --job-uid ${JOB_UID}
      --job-run-uid ${CI_PIPELINE_ID}
      --job-run-url ${CI_PIPELINE_URL}
      --launch-finish
      /allure-results || true
    - docker compose ps -a
    - docker compose down --rmi local || true
    - docker compose ps -a
    - ALLURE_URL=$(docker compose run --rm --quiet-pull allure upload --ci-type gitlab --job-uid ${JOB_UID} --job-run-uid ${CI_PIPELINE_ID} --job-run-url ${CI_PIPELINE_URL} /allure-results 2>&1 | grep -o 'https://allure\.2gis\.dev/jobrun/[0-9]\+' | head -n1)
    - echo "{\"Reports\":[{\"external_link\":{\"label\":\"Allure\",\"url\":\"${ALLURE_URL}\"}}]}" > annotation.json
  artifacts:
    when: always
    paths:
      - docker/annotation.json
    expire_in: 1 days
    reports:
      annotations: docker/annotation.json

.update_snapshots:
  stage: ui test
  tags: [io, docker-compose]
  variables:
    SNAPSHOT_BRANCH: snapshots/${CI_COMMIT_REF_NAME}
  before_script:
    - docker build -t playwright-docs -f ./docker/Dockerfile.playwright .
  script:
    - >
      docker run --rm --ipc=host
      -v ./tests:/app/tests
      -v ./src:/app/src
      -v ./tsconfig.json:/app/tsconfig.json
      -v ./playwright.config.ts:/app/playwright.config.ts
      -e APP_URL=${APP_URL}
      -e CI=${CI}
      playwright-docs
      npm run screen:test:update

    - git config user.email "gefest-dev@2gis.ru"
    - git config user.name "ci-bot"

    - git checkout -b ${SNAPSHOT_BRANCH}
    - git add tests/screen/**/*.png
    - |
      if ! git diff --cached --quiet; then
        git commit -m "chore: update snapshots for ${CI_COMMIT_REF_NAME}"
        git remote set-url origin https://gitlab-ci-token:${GIT_PUSH_USER_TOKEN}@gitlab.2gis.ru/gefest/frontend/dociverse.git
        git push --force \
             -o merge_request.create \
             -o merge_request.target="${CI_COMMIT_REF_NAME}" \
             -o merge_request.title="Update snapshots for ${CI_COMMIT_SHORT_SHA}" \
             origin ${SNAPSHOT_BRANCH}
      else
        echo "No screenshot updates found."
      fi
  after_script:
    - git config --unset user.name
    - git config --unset user.email
    - git remote set-url origin ${CI_REPOSITORY_URL}
