import { join } from 'node:path';
import { writeFile, mkdir } from 'node:fs/promises';
import {
  SidebarCategoriesShorthand,
  SidebarItemAutogenerated,
  SidebarItemCategoryConfig,
  SidebarItemConfig,
} from '@docusaurus/plugin-content-docs/lib/sidebars/types.js';
import { sortSemverList } from '../lib/sortSemverList';
import { SidebarInfoMap } from '../types/plugin';
import { getReferenceSidebarTemplate } from '../lib/getReferenceSidebarTemplate';

type Sidebars = (
  | SidebarItemAutogenerated
  | {
      type: 'category';
      label: string;
      items: SidebarCategoriesShorthand | SidebarItemConfig[];
    }
)[];

/**
 * Создает файл с заменами для всех сайдбаров на основе данных из манифестов
 *
 * @param sidebarInfoMap Полная карта всех replaceId и их данных
 */
export async function buildReferenceSidebars(sidebarInfoMap: SidebarInfoMap): Promise<void> {
  const rootDir = process.cwd();
  const sidebarPath = join(rootDir, 'node_modules', '.cache', 'sdkSidebars', 'sdkSidebars.json');

  const replacements: Record<string, SidebarItemCategoryConfig> = {};

  Object.entries(sidebarInfoMap).forEach(([replaceId, groups]) => {
    const allSidebarItems: Sidebars = [];

    groups.forEach((group) => {
      const sidebarItems = Object.entries(group.versions).map(([version, dirName]) =>
        getReferenceSidebarTemplate(version, dirName, group.sidebar.showVersions),
      );

      const sortedItems = group.sidebar.showVersions
        ? sortSemverList(sidebarItems as SidebarItemCategoryConfig[])
        : sidebarItems;

      const visibleItems = group.sidebar.showOnlyLatest ? sortedItems.slice(0, 1) : sortedItems;

      allSidebarItems.push(...visibleItems);
    });

    replacements[replaceId] = {
      type: 'category',
      label: 'Справочник API',
      items: allSidebarItems,
      key: replaceId.replace(/\//g, '-'),
    };
  });

  await mkdir(join(rootDir, 'node_modules', '.cache', 'sdkSidebars'), { recursive: true });
  await writeFile(sidebarPath, JSON.stringify(replacements, null, 2), 'utf8');
}
