FROM docker-hub.2gis.ru/mcr-microsoft-com/playwright:v1.55.0-noble

WORKDIR /app
COPY package.json package-lock.json ./

RUN npm config set registry https://nexus.2gis.dev/repository/npm-group/ \
    && npm ci
