apiVersion: v2
name: kit-docs
type: application
description: 2GIS/Urbi kit documentation built with Docusaurus

version: 0.0.1
appVersion: latest

maintainers:
  - name: gefest
    url: https://gitlab.2gis.ru/gefest/frontend/dociverse
    email: gefest@2gis.ru
