import {
  SidebarItemAutogenerated,
  SidebarItemCategoryConfig,
} from '@docusaurus/plugin-content-docs/lib/sidebars/types.js';

export const getReferenceSidebarTemplate = (
  label: string,
  dirName: string,
  showVersion: boolean,
): SidebarItemCategoryConfig | SidebarItemAutogenerated => {
  if (showVersion) {
    return {
      type: 'category',
      label,
      items: [
        {
          type: 'autogenerated',
          dirName,
        },
      ],
    };
  }

  return {
    type: 'autogenerated',
    dirName,
  };
};
