import { SidebarItem } from '@docusaurus/plugin-content-docs/lib/sidebars/types.js';
import {
  SidebarItemAutogenerated,
  SidebarItemCategoryConfig,
} from '@docusaurus/plugin-content-docs/lib/sidebars/types.js';

export function sidebarItemReplace(
  obj: Record<string, SidebarItem[]>,
  placeholder: string,
  replacement: SidebarItemCategoryConfig | SidebarItemAutogenerated,
): void {
  let replaced = false;

  const onReplace = (wasReplaced: boolean) => {
    replaced ||= wasReplaced;
  };

  for (const key in obj) {
    obj[key] = obj[key].map((item) => deepReplace(item, placeholder, replacement, onReplace));
  }

  if (!replaced) {
    throw new Error(`Ошибка при замене ${placeholder}: данный id не найден`);
  }
}

function deepReplace(
  item: SidebarItem,
  placeholder: string,
  replacement: SidebarItemCategoryConfig | SidebarItemAutogenerated,
  onReplace: (wasReplaced: boolean) => void,
): SidebarItem {
  if (item.customProps?.replaceId === placeholder) {
    onReplace(true);
    return replacement as SidebarItem;
  }

  if ('items' in item && Array.isArray(item.items)) {
    item.items = item.items.map((child) => deepReplace(child, placeholder, replacement, onReplace));
  }

  return item;
}
