# Тянем джобы для проведения SAST-анализа и SCA (Software Composition Analysis) из общего репозитория
# Делаем это тут вместо общего include, чтобы не блокировать другие пайплайны в случае недоступности traffic/cicd-pipelines
include:
  - project: 'traffic/cicd-pipelines'
    ref: master
    file:
      - pipelines/dependency-check.yml
      - sast.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"

variables:
  HELM_RELEASE_NAME_BASE: kit-docs
  IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
  DEPS_IMAGE: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${DEPS_IMAGE_NAME}:${IMAGE_TAG}

.ai mr common:
  stage: tools
  needs: []
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual

ai review:
  variables:
    PROMPT_FILE: .ai/pr-agent/review-improve.md
  extends: [.ai review, .ai mr common]

ai describe:
  extends: [.ai describe, .ai mr common]

ai improve:
  variables:
    PROMPT_FILE: .ai/pr-agent/review-improve.md
  extends: [.ai improve, .ai mr common]

.mr rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    - when: never

.mr rules manual:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    - when: never

# Общие правила и переменные для security jobs
.security_base:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH && $CI_OPEN_MERGE_REQUESTS
  variables:
    VAULT_TEAM: gefest

# SAST
# https://confluence.2gis.ru/pages/viewpage.action?pageId=559152401
sast:scan:
  extends:
    - .appscreener_scan
    - .security_base

# SCA
# https://confluence.2gis.ru/pages/viewpage.action?pageId=559144390
sca:scan:
  extends:
    - .dependency-check
    - .security_base

deps build:
  extends: [.build deps, .mr rules]
  needs: []
  interruptible: true

.app build:
  needs: [deps build]
  extends: [.build app]
  interruptible: true
  environment:
    name: ${CI_COMMIT_REF_NAME}/${DISTRIBUTION_MODE}/${BRAND}
    auto_stop_in: 1 month
  variables:
    HELM_RELEASE_NAME: ${HELM_RELEASE_NAME_BASE}-${CI_ENVIRONMENT_SLUG}
    APP_URL: https://${HELM_RELEASE_NAME}.web-staging.2gis.ru
    APIKEY_MAPGL: ${APIKEY_MAPGL_DEMO}
    APIKEY_MAPGL_JSFIDDLE: ${APIKEY_MAPGL_JSFIDDLE_DEMO}
    APIKEY_NAVIGATION: ${APIKEY_NAVIGATION_DEMO}
    APIKEY_PLACES: ${APIKEY_PLACES_DEMO}
    SEARCH_API_URL: http://docs-search-api.doka.svc.cluster.local
    APIKEY_DOCS_SEARCH: ${APIKEY_DOCS_SEARCH_STAGING}
    CHAT_BOT_API_URL: http://twogis-api-docs-search.ai.svc.cluster.local
    S3_BUCKET_NAME: ${S3_BUCKET_STAGING}

2gis build:
  extends: [.app build, .mr rules]
  variables:
    BRAND: 2gis
    DISTRIBUTION_MODE: public
    APP_IMAGE: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${APP_IMAGE_NAME_2GIS}:${IMAGE_TAG}
    SEARCH_API_COLLECTION: 2gis-kit-docs
    UX_FEEDBACK_ID: ${UX_FEEDBACK_ID_2GIS}

private 2gis build:
  extends: [.app build, .mr rules manual]
  variables:
    BRAND: 2gis
    DISTRIBUTION_MODE: private
    APP_IMAGE: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${APP_IMAGE_NAME_2GIS_PRIVATE}:${IMAGE_TAG}
    SEARCH_API_COLLECTION: 2gis-kit-docs

urbi build:
  extends: [.app build, .mr rules]
  variables:
    BRAND: urbi
    DISTRIBUTION_MODE: public
    APP_IMAGE: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${APP_IMAGE_NAME_URBI}:${IMAGE_TAG}
    SEARCH_API_COLLECTION: urbi-kit-docs

helm lint:
  extends: [.helm lint, .mr rules]

test dev:
  extends: [.tests_dev, .mr rules]
  needs: [deps build]
  script:
    - !reference [.tests_dev, script]
    - npm run test:env:ci-dev

.review:
  stage: review
  extends: [.deploy app, .mr rules]
  variables:
    HELM_RELEASE_NAME: ${HELM_RELEASE_NAME_BASE}-${CI_ENVIRONMENT_SLUG}
    DOMAINS: ${HELM_RELEASE_NAME}
    DC: n3
    CLUSTER: staging
    HELM_VALUES_EXTRA: ./deploy/kit-docs/values.staging.yaml
  environment:
    name: ${CI_COMMIT_REF_NAME}/${DISTRIBUTION_MODE}/${BRAND}
    url: https://${HELM_RELEASE_NAME}.web-staging.2gis.ru
    auto_stop_in: 1 month

2gis review:
  extends: [.review]
  needs: [2gis build, helm lint, s3 sync]
  variables:
    BRAND: 2gis
    DISTRIBUTION_MODE: public
    APP_IMAGE_NAME: ${APP_IMAGE_NAME_2GIS}
  environment:
    on_stop: 2gis stop review

private 2gis review:
  extends: [.review]
  needs: [private 2gis build, helm lint, s3 sync]
  variables:
    BRAND: 2gis
    DISTRIBUTION_MODE: private
    APP_IMAGE_NAME: ${APP_IMAGE_NAME_2GIS_PRIVATE}
  environment:
    on_stop: private 2gis stop review

urbi review:
  extends: [.review, .mr rules manual]
  needs: [urbi build, helm lint, s3 sync]
  variables:
    BRAND: urbi
    DISTRIBUTION_MODE: public
    APP_IMAGE_NAME: ${APP_IMAGE_NAME_URBI}
  environment:
    on_stop: urbi stop review

.stop review:
  stage: stop review
  image:
    name: alpine/helm:3.14.0
    entrypoint: ['']
  tags: [io, docker-exec]
  environment:
    action: stop
    name: ${CI_COMMIT_REF_NAME}/${DISTRIBUTION_MODE}/${BRAND}
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  script:
    - !reference [.echo global envs, script]
    - helm --kube-context staging-n3 uninstall ${HELM_RELEASE_NAME_BASE}-${CI_ENVIRONMENT_SLUG}

2gis stop review:
  extends: [.stop review]
  needs: [2gis review]
  variables:
    BRAND: 2gis
    DISTRIBUTION_MODE: public

private 2gis stop review:
  extends: [.stop review]
  needs: [private 2gis review]
  variables:
    BRAND: 2gis
    DISTRIBUTION_MODE: private

urbi stop review:
  extends: [.stop review]
  needs: [urbi review]
  variables:
    BRAND: urbi
    DISTRIBUTION_MODE: public

test screen:
  extends: [.tests_screen, .mr rules]
  needs: [2gis review]
  variables:
    HELM_RELEASE_NAME: ${HELM_RELEASE_NAME_BASE}-${CI_ENVIRONMENT_SLUG}
    APP_URL: https://${HELM_RELEASE_NAME}.web-staging.2gis.ru
  environment:
    name: ${CI_COMMIT_REF_NAME}/public/2gis

update snapshots:
  extends: [.update_snapshots, .mr rules manual]
  needs: [2gis review]
  variables:
    HELM_RELEASE_NAME: ${HELM_RELEASE_NAME_BASE}-${CI_ENVIRONMENT_SLUG}
    APP_URL: https://${HELM_RELEASE_NAME}.web-staging.2gis.ru
  environment:
    name: ${CI_COMMIT_REF_NAME}/public/2gis

s3 sync:
  extends: [.s3 sync, .mr rules]
  variables:
    S3_BUCKET_NAME: ${S3_BUCKET_STAGING}
    S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID_STAGING}
    S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY_STAGING}
